name: Deploy wordpress to eks

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Credential AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1 

      - name: Update kubeconfig to access AWS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name swile-cluster2

      - name: APply deployment for eks
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Check created resources
        run: | 
          kubectl get pods
          kubectl get svc